### ISSUE TITLE
Error running umis tagcount with 1.0.3 (working on 1.0.0)

### ISSUE THREAD

**Issue by magali** [vals/umis#55]
Hello!

I had a script that was working when using umis version 1.0.0.

However, it now raises an error with version 1.0.3 when counting the tags.

The commend is:
umis tagcount AACAGCT.bam AACAGCT.txt

The error I get (with 1.0.3):
Traceback (most recent call last):
  File "/services/tools/anaconda3/4.4.0/bin/umis", line 10, in <module>
    sys.exit(umis())
  File "/services/tools/anaconda3/4.4.0/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/services/tools/anaconda3/4.4.0/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/services/tools/anaconda3/4.4.0/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/services/tools/anaconda3/4.4.0/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/services/tools/anaconda3/4.4.0/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/services/tools/anaconda3/4.4.0/lib/python3.6/site-packages/umis/umis.py", line 459, in tagcount
    from utils import weigh_evidence
ImportError: cannot import name 'weigh_evidence'

The version on the server is now 1.0.3 and I would like my script to work with the latest version.

Is there any bug you can fix and/or something I can do differently?

Thanks a lot,
Magali

**Comment by roryk** [comment]
Hi Magali,

It seems like something is borked with your umis installation and it is missing the `utils.pyx` file, do you think you could try reinstalling it? I see you are using anaconda, is your umis installation from bioconda or from somewhere else? If it is from somewhere else, the bioconda package works well and you can install it just by doing:

```
conda install -c bioconda umis
```

**Comment by magali** [comment]
Hi Roryk! 

Thank you so much for your quick and useful reply.
It seems indeed that this is a problem with the installation.
I have not done the previous installation myself as I'm working on an administered server, but I have now created a conda environment and installed umis with the bioconda command you suggested and it seems to work now fine within this environment. :-)

Thanks!
Magali

**Comment by roryk** [comment]
Hi Magali,

Great! Glad that helped! conda is so nice because you can just make your own installation of everything and not have to bug the sysadmins to work around problems like this. :)
